projects:
  AmplifyAndroid:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: btftjooytbeyvekocipbgz43ra
      endpoints:
        prod: >-
          https://oqydy7gofbdpfe6gkxbsnxuhny.appsync-api.ap-southeast-1.amazonaws.com/graphql
