platform :ios, '9.0'

target :'iOS-viaPatron' do
  use_frameworks!

  # Pods for iOS-viaPatron
  pod 'AWSCore', '~> 2.8.0'
  pod 'AWSAppSync', '~> 2.8.0'
  pod 'AWSMobileClient', '~> 2.8.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.8.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.8.0'   # Optional dependency required to use drop-in UI
end
